version: '3.9'
services:
  cdk:
    build: 
      context: .
      dockerfile: ./container/cdk/Dockerfile
    volumes:
      - type: bind
        source: ./cdk
        target: /cdk
    tty: true
  app:
    build: 
      context: .
      dockerfile: ./container/app/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./.aws
        target: /.aws/
    tty: true
